### ISSUE TITLE
imam ptroblem

### ISSUE THREAD

**Issue by denishristov** [VitoNaychev/netprog#1]
ne mi se kompilira koda dava mi Not enought enought space: ESEIONCODY
sushto ne razbiram zashto game tryabva da nasledyava karina smisul znam che igrata e tumor ama spored men tova prechi na S v SOLID principa na OOPtop i ne otgovatya samo za ena otgovornost 4.7/5 po dobre ot kolegata mi koito pishe bek end

**Comment by VitoNaychev** [comment]
1 gram treva i si zatvarqsh ochite

**Comment by denishristov** [comment]
navit
